---
- name: Deploy a Terraform infrastructure
  hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: terraform_vm
      vars:
        terraform_vm_project_path: /home/vez/homelab/terraform/projects/terransible
        # terraform_vars_vm_attr:
        #   mast:
        #     ram: 2048
        #     cpu: 2
        #     vlan: 66
        #   work:
        #     ram: 1024
        #     cpu: 1
            # vlan: 66

- name: Ping
  hosts: servers
  gather_facts: false
  tasks:
    - name: Ping the host group
      ansible.builtin.ping: